### ISSUE TITLE
pip install -r requirements.txt installs version of estasticsearch_dsl that is missing FacetedSearch

### ISSUE THREAD

**Issue by gojefferson** [HonzaKral/es-django-example#3]
I was able to get a version of the `estaticsearch_dsl` with FacetedSearch included from GitHub, but that apparently is not the version on PyPi. 

Here's the traceback from running the migrate command:

```
(es-django)> python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Jeff1/.virtualenvs/es-django/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/Jeff1/.virtualenvs/es-django/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/Jeff1/.virtualenvs/es-django/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Jeff1/.virtualenvs/es-django/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/Jeff1/.virtualenvs/es-django/lib/python2.7/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Jeff1/Desktop/es-django-example/qa/apps.py", line 7, in <module>
    from .search import Question, Answer
  File "/Users/Jeff1/Desktop/es-django-example/qa/search.py", line 3, in <module>
    from elasticsearch_dsl import (
ImportError: cannot import name FacetedSearch
(es-django)> 
```

**Comment by honzakral** [comment]
This is resolved with the `0.0.5` release of elasticsearch_dsl

Thanks!
